### ISSUE TITLE
Test suite fails is the `aggdraw` is not available

### ISSUE THREAD

**Issue by avalentino** [pytroll/pycoast#4]
```
======================================================================
ERROR: test_add_polygon_agg (pycoast.tests.test_pycoast.TestPILAGG)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/build-area/pycoast-0.5.4/pycoast/tests/test_pycoast.py", line 495, in test_add_polygon_agg
    cw.add_polygon(img, area_def, polygons['REYKJAVIK_ATC'], outline='red', width=2)
TypeError: add_polygon() got an unexpected keyword argument 'width'

======================================================================
ERROR: test_add_shapefile_shapes_agg (pycoast.tests.test_pycoast.TestPILAGG)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/build-area/pycoast-0.5.4/pycoast/tests/test_pycoast.py", line 518, in test_add_shapefile_shapes_agg
    outline='red', width=2)
TypeError: add_shapefile_shapes() got an unexpected keyword argument 'width'

======================================================================
ERROR: test_europe_agg (pycoast.tests.test_pycoast.TestPILAGG)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/build-area/pycoast-0.5.4/pycoast/tests/test_pycoast.py", line 321, in test_europe_agg
    cw.add_rivers(img, area_def, level=5, outline='blue', width=0.5, outline_opacity=127)
TypeError: add_rivers() got an unexpected keyword argument 'width'

======================================================================
ERROR: test_europe_agg_file (pycoast.tests.test_pycoast.TestPILAGG)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/build-area/pycoast-0.5.4/pycoast/tests/test_pycoast.py", line 338, in test_europe_agg_file
    width=0.5, outline_opacity=127)
TypeError: add_rivers_to_file() got an unexpected keyword argument 'width'

======================================================================
ERROR: test_geos_agg (pycoast.tests.test_pycoast.TestPILAGG)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/build-area/pycoast-0.5.4/pycoast/tests/test_pycoast.py", line 357, in test_geos_agg
    cw.add_coastlines(img, (proj4_string, area_extent), resolution='l', width=0.5)
TypeError: add_coastlines() got an unexpected keyword argument 'width'

======================================================================
ERROR: test_grid_agg (pycoast.tests.test_pycoast.TestPILAGG)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/build-area/pycoast-0.5.4/pycoast/tests/test_pycoast.py", line 378, in test_grid_agg
    minor_is_tick=False)
TypeError: add_grid() got an unexpected keyword argument 'outline_opacity'

======================================================================
ERROR: test_grid_agg_file (pycoast.tests.test_pycoast.TestPILAGG)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/build-area/pycoast-0.5.4/pycoast/tests/test_pycoast.py", line 440, in test_grid_agg_file
    minor_is_tick=False)
TypeError: add_grid_to_file() got an unexpected keyword argument 'outline_opacity'

======================================================================
ERROR: test_grid_agg_txt (pycoast.tests.test_pycoast.TestPILAGG)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/build-area/pycoast-0.5.4/pycoast/tests/test_pycoast.py", line 384, in test_grid_agg_txt
    import aggdraw
ImportError: No module named aggdraw

======================================================================
ERROR: test_grid_nh_agg (pycoast.tests.test_pycoast.TestPILAGG)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/build-area/pycoast-0.5.4/pycoast/tests/test_pycoast.py", line 447, in test_grid_nh_agg
    import aggdraw
ImportError: No module named aggdraw

======================================================================
FAIL: test_dateline_boundary_cross (pycoast.tests.test_pycoast.TestPIL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/build-area/pycoast-0.5.4/pycoast/tests/test_pycoast.py", line 227, in test_dateline_boundary_cross
    self.failUnless(fft_metric(dl_data, res), 'Writing of dateline boundary crossing data failed')
AssertionError: Writing of dateline boundary crossing data failed

======================================================================
FAIL: test_dateline_cross (pycoast.tests.test_pycoast.TestPIL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/build-area/pycoast-0.5.4/pycoast/tests/test_pycoast.py", line 206, in test_dateline_cross
    self.failUnless(fft_metric(dl_data, res), 'Writing of dateline crossing data failed')
AssertionError: Writing of dateline crossing data failed

======================================================================
FAIL: test_grid (pycoast.tests.test_pycoast.TestPIL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/build-area/pycoast-0.5.4/pycoast/tests/test_pycoast.py", line 151, in test_grid
    self.failUnless(fft_metric(grid_data, res), 'Writing of grid failed')
AssertionError: Writing of grid failed

======================================================================
FAIL: test_grid_file (pycoast.tests.test_pycoast.TestPIL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/build-area/pycoast-0.5.4/pycoast/tests/test_pycoast.py", line 185, in test_grid_file
    self.failUnless(fft_metric(grid_data, res), 'Writing of grid failed')
AssertionError: Writing of grid failed

======================================================================
FAIL: test_grid_nh (pycoast.tests.test_pycoast.TestPIL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/build-area/pycoast-0.5.4/pycoast/tests/test_pycoast.py", line 247, in test_grid_nh
    self.failUnless(fft_metric(grid_data, res), 'Writing of nh grid failed')
AssertionError: Writing of nh grid failed

======================================================================
FAIL: test_grid_geos_agg (pycoast.tests.test_pycoast.TestPILAGG)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/build-area/pycoast-0.5.4/pycoast/tests/test_pycoast.py", line 422, in test_grid_geos_agg
    self.failUnless(fft_metric(geos_data, res), 'Writing of geos contours failed')
AssertionError: Writing of geos contours failed

----------------------------------------------------------------------
Ran 21 tests in 14.014s

FAILED (failures=6, errors=9)
```

**Comment by avalentino** [comment]
Hi, any news on this?
I'm trying to push pycoast 0.5.4 into debian and this issue seems to be blocking.

I prepared a patch to ship test that use ContourWriterAGG 

```diff
diff --git a/pycoast/tests/test_pycoast.py b/pycoast/tests/test_pycoast.py
index 8675a58..98e61bf 100644
--- a/pycoast/tests/test_pycoast.py
+++ b/pycoast/tests/test_pycoast.py
@@ -21,7 +21,7 @@ import unittest
 import numpy as np
 from PIL import Image, ImageFont
 
-from pycoast import ContourWriter
+from pycoast import ContourWriter, ContourWriterAGG
 
 
 def tmp(f):
@@ -305,6 +305,7 @@ class TestPIL(TestPycoast):
         self.failUnless(fft_metric(grid_data, res), 'Writing of Brazil shapefiles failed')
 
 
+@unittest.skipIf(ContourWriterAGG is ContourWriter, 'aggdraw not available')
 class TestPILAGG(TestPycoast):
     def test_europe_agg(self):
         from pycoast import ContourWriterAGG
```

but there are still 5 tests failing:

```
$ python setup.py test
running test
running egg_info
writing requirements to pycoast.egg-info/requires.txt
writing pycoast.egg-info/PKG-INFO
writing top-level names to pycoast.egg-info/top_level.txt
writing dependency_links to pycoast.egg-info/dependency_links.txt
reading manifest file 'pycoast.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'test/*.png'
writing manifest file 'pycoast.egg-info/SOURCES.txt'
running build_ext
test_add_polygon (pycoast.tests.test_pycoast.TestPIL) ... ok
test_add_shapefile_shapes (pycoast.tests.test_pycoast.TestPIL) ... ok
test_dateline_boundary_cross (pycoast.tests.test_pycoast.TestPIL) ... FAIL
test_dateline_cross (pycoast.tests.test_pycoast.TestPIL) ... FAIL
test_europe (pycoast.tests.test_pycoast.TestPIL) ... ok
test_europe_file (pycoast.tests.test_pycoast.TestPIL) ... ok
test_geos (pycoast.tests.test_pycoast.TestPIL) ... ok
test_grid (pycoast.tests.test_pycoast.TestPIL) ... FAIL
test_grid_file (pycoast.tests.test_pycoast.TestPIL) ... FAIL
test_grid_geos (pycoast.tests.test_pycoast.TestPIL) ... ok
test_grid_nh (pycoast.tests.test_pycoast.TestPIL) ... FAIL
test_add_polygon_agg (pycoast.tests.test_pycoast.TestPILAGG) ... skipped 'aggdraw not available'
test_add_shapefile_shapes_agg (pycoast.tests.test_pycoast.TestPILAGG) ... skipped 'aggdraw not available'
test_europe_agg (pycoast.tests.test_pycoast.TestPILAGG) ... skipped 'aggdraw not available'
test_europe_agg_file (pycoast.tests.test_pycoast.TestPILAGG) ... skipped 'aggdraw not available'
test_geos_agg (pycoast.tests.test_pycoast.TestPILAGG) ... skipped 'aggdraw not available'
test_grid_agg (pycoast.tests.test_pycoast.TestPILAGG) ... skipped 'aggdraw not available'
test_grid_agg_file (pycoast.tests.test_pycoast.TestPILAGG) ... skipped 'aggdraw not available'
test_grid_agg_txt (pycoast.tests.test_pycoast.TestPILAGG) ... skipped 'aggdraw not available'
test_grid_geos_agg (pycoast.tests.test_pycoast.TestPILAGG) ... skipped 'aggdraw not available'
test_grid_nh_agg (pycoast.tests.test_pycoast.TestPILAGG) ... skipped 'aggdraw not available'

======================================================================
FAIL: test_dateline_boundary_cross (pycoast.tests.test_pycoast.TestPIL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/pycoast/pycoast/tests/test_pycoast.py", line 227, in test_dateline_boundary_cross
    self.failUnless(fft_metric(dl_data, res), 'Writing of dateline boundary crossing data failed')
AssertionError: Writing of dateline boundary crossing data failed

======================================================================
FAIL: test_dateline_cross (pycoast.tests.test_pycoast.TestPIL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/pycoast/pycoast/tests/test_pycoast.py", line 206, in test_dateline_cross
    self.failUnless(fft_metric(dl_data, res), 'Writing of dateline crossing data failed')
AssertionError: Writing of dateline crossing data failed

======================================================================
FAIL: test_grid (pycoast.tests.test_pycoast.TestPIL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/pycoast/pycoast/tests/test_pycoast.py", line 151, in test_grid
    self.failUnless(fft_metric(grid_data, res), 'Writing of grid failed')
AssertionError: Writing of grid failed

======================================================================
FAIL: test_grid_file (pycoast.tests.test_pycoast.TestPIL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/pycoast/pycoast/tests/test_pycoast.py", line 185, in test_grid_file
    self.failUnless(fft_metric(grid_data, res), 'Writing of grid failed')
AssertionError: Writing of grid failed

======================================================================
FAIL: test_grid_nh (pycoast.tests.test_pycoast.TestPIL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/pycoast/pycoast/tests/test_pycoast.py", line 247, in test_grid_nh
    self.failUnless(fft_metric(grid_data, res), 'Writing of nh grid failed')
AssertionError: Writing of nh grid failed

----------------------------------------------------------------------
Ran 21 tests in 11.832s

FAILED (failures=5, skipped=10)
```

**Comment by mraspaud** [comment]
@avalentino the problem with these unit tests is that they match a newly created image with a reference image, and that the images can vary slightly depending in the system they are generated on. We can for example see differences between Fedora and Ubuntu...

So what you could do is replace the reference images with the ones generated by your system (if you see they are close enough that is) in your packaging branch...

Otherwise your patch looks good, feel free to make a PR

As a side note AGG, @adybbroe and @northaholic been working on a cairo port so that AGG could be ditched.

**Comment by avalentino** [comment]
> So what you could do is replace the reference images with the ones generated by your system (if you see they are close enough that is) in your packaging branch...

do you mean the ones generated by the test itself?

**Comment by mraspaud** [comment]
yes
